// trivia-game-svelte/src/screens/Welcome.svelte
<Container>
  <H1 data-testid='welcome-header'>Welcome to the Trivia Challenge</H1>
  <TextContainer>
    <P>You will be presented with 10 true or false questions.</P>
    <P>Can you score 100%?</P>
  </TextContainer>
  <Button on:onClick={startQuiz} data-testid='begin-button'>
    Begin
  </Button>
</Container>

<script>
  import Button from '../components/Button.svelte'
  import Container from '../components/Container.svelte'
  import H1 from '../components/H1.svelte'
  import P from '../components/P.svelte'
  import TextContainer from '../components/TextContainer.svelte'
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();
  
	function startQuiz() {
    dispatch('startQuiz')
	}
</script>

// trivia-game-vue/src/screens/Welcome.vue
<template>
  <Container>
    <H1 data-testid='welcome-header'>Welcome to the Trivia Challenge</H1>
    <TextContainer>
      <P>You will be presented with 10 true or false questions.</P>
      <P>Can you score 100%?</P>
    </TextContainer>
    <Button :onClick="startQuiz" data-testid='begin-button'>
      Begin
    </Button>
  </Container>
</template>

<script>
import Button from '../components/Button.vue'
import Container from '../components/Container.vue'
import H1 from '../components/H1.vue'
import P from '../components/P.vue'
import TextContainer from '../components/TextContainer.vue'

export default {
  name: "Welcome",
  components: {
    Button,
    Container,
    H1,
    P,
    TextContainer
  },
  methods: {
    startQuiz() {
      this.$emit('startQuiz')
    }
  }
}
</script>
